### ISSUE TITLE
Add support for recursive variants

### ISSUE THREAD

**Issue by Georacer** [AvyFly/parasect#73]
Right now only two levels are supported.

**Comment by flyasky** [comment]
do you mean sub variants?
 like,
```
variants:
  a:
    common:
       ingredients:
         - [...]
    variants:
      a_1:
        common:
          ingredients:
            - [...]
```
